/**
 * MazeGenerator.h
 *
 * By Sebastian Raaphorst, 2018.
 */

#pragma once

#include <map>

#include "MazeGraph.h"

namespace spelunker::graphmaze {

    /**
     * Abstract case for a graph generator.
     * Given a MazeGraph and a subclass of this class, which embodies an
     * essential algorithm, derive a Maze.
     */
    class MazeGenerator {
    public:
        MazeGenerator() = default;

        /**
         * Generate a maze using the given technique of size width by height.
         * @param tmplt the template graph, as described above
         * @return the maze generated by the algorithm
         */
        virtual const MazeGraph generate(const MazeGraph &tmplt) const = 0;
    };
}
